[tools]
lua = "latest"
stylua = "2.3.1"
selene = "0.29.0"

[tool_alias]
selene = "https://github.com/quentin-rodriguez/mise-selene.git"

[tasks.lint]
description = "Lint lua scripts"
run = "selene init.lua lua/ tests/"


[tasks.format]
description = "Format lua scripts"
run = "stylua init.lua lua/ tests/"
