[tools]
lua = "latest"
stylua = "2.3.1"
selene = "0.29.0"

[alias]
selene = "https://github.com/quentin-rodriguez/mise-selene.git"

[tasks.format]
description = "Format lua scripts"
run = "stylua init.lua lua/"
