--- @class TreesitterConfig
--- @field modules {[string]:TreesitterModule}?
--- @field sync_install boolean?
--- @field ensure_installed string[]|string
--- @field ignore_install string[]?
--- @field auto_install boolean?
--- @field parser_install_dir string?
--- @see https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/configs.lua

--- @class TreesitterModule
--- @field module_path string?
--- @field enable boolean|string[]|function(string): boolean?
--- @field disble boolean|string[]|function(string): boolean?
--- @field keymaps table<string, string>?
--- @field is_supported function(string): string?
--- @field attach function(string)?
--- @field detach function(string)?
--- @field enabled_buffers table<integer, boolean>?
--- @field additional_vim_regex_highlighting boolean|string[]?
--- @see https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/configs.lua

--- @class BlinkCmpConfig
