name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  links:
    name: Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress README.md
          fail: true

  format:
    name: Formatting check with Stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 2.3.1
          args: --check init.lua lua/

  lint:
    name: Linter check with Selene
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.29.0
          args: --display-style=quiet init.lua lua/

  test:
    name: Testing check with Neovim
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: folke/github/neovim@main
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libreadline-dev
      - uses: actions/cache@v6
        with:
          path: .tests
          key: ${{ runner.os }}-tests-${{ hashFiles('tests/minit.lua') }}
      - name: Run tests
        run: nvim -l tests/minit.lua
