name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  selene:
    name: Linter check with selene
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.29.0
          args: --display-style=quiet init.lua lua/

